jwt-secret-key: shhhh
database:
  mysql:
    host: localhost
    username: service
    password: service
  postgres:
    host: localhost
    username: service
    password: service
kafka:
  host: localhost
  port: 9092
