jwt-secret-key: shhhh
database:
  mysql:
    host: localhost
    username: service
    password: user-service
  postgres:
    host: localhost
    username: service
    password: twofa-service
kafka:
  host: localhost
  port: 9092
