jwt-secret-key: shhhh
database:
  mysql:
    host: localhost
    username: service
    password: service
  postgres:
    host: localhost
    username: service
    password: service
  cassandra:
    host: localhost
    username: cassandra
    password: tripconnect3107
  elasticsearch:
    host: localhost
discovery:
  address: "localhost:31079"
kafka:
  host: localhost
  port: 9092
uuid:
  namespace: 00000000-00000000-00000000-00000000
